### ISSUE TITLE
The databinding needs more explanation

### ISSUE THREAD

**Issue by user135711** [aspnet/Blazor.Docs#110]
Excellent introduction. One place for improvement: The databinding didn't make sense. The statement "The Year parameter is bindable because it has a companion YearChanged event that matches the type of the Year parameter." needs to explain the action. Also, what is format-value in `<input bind="@StartDate" format-value="yyyy-MM-dd" />` Is this a blazor tag-helper? That needs explanation.

**Comment by guardrex** [comment]
References:

* https://github.com/aspnet/Blazor/blob/e90432c7255675e1b998ee1d51cad70b0e005d1e/src/Microsoft.AspNetCore.Blazor.Razor.Extensions/BindLoweringPass.cs#L388-L409
* https://github.com/aspnet/Blazor/blob/e90432c7255675e1b998ee1d51cad70b0e005d1e/src/Microsoft.AspNetCore.Blazor.Razor.Extensions/BindTagHelperDescriptorProvider.cs#L156-L167
