### ISSUE TITLE
Class name and constructor name does not match

### ISSUE THREAD

**Issue by miroslavp** [aspnet/Blazor.Docs#112]
In the [Dependency injection in services](https://blazor.net/docs/dependency-injection.html#dependency-injection-in-services) section,
the class and the constructor don’t match

public class **DataAccess** : IDataAccess
{
    // The constructor receives an HttpClient via dependency
    // injection. HttpClient is a default service offered by Blazor.
    public **Repository**(HttpClient client)
    {
        ...
    }
    ...
}

**Comment by guardrex** [comment]
ping @rstropek
