### ISSUE TITLE
Update app base path content to mention NavLinks

### ISSUE THREAD

**Issue by guardrex** [aspnet/Blazor.Docs#131]
For https://blazor.net/docs/host-and-deploy/index.html#app-base-path, surface that `NavLink`s must also receive the URL segment to work. The current text adequately covers the **\<base>** tag but nothing is mentioned about the `NavLink`s.

**Comment by guardrex** [comment]
@danroth27 This is fixed by https://github.com/aspnet/Blazor/issues/845, correct?

There should be no need now to add the base path to `NavLink`s.

**Comment by danroth27** [comment]
Correct.
