### ISSUE TITLE
Document Route parameters with type

### ISSUE THREAD

**Issue by vertonghenb** [aspnet/Blazor.Docs#183]
Existing Topic: https://blazor.net/docs/routing.html

Currenty it's possible to cast the parameter directly to the property type by adding `:type`. Currently it's not yet supported in the docs.
 
**An example code snippet:**

```csharp
@page "/Users"
@page "/Users/{Id:int}"

<h1>The user Id is @Id !</h1>

@functions {
    [Parameter]    private int Id { get; set; }
}
```

**Comment by guardrex** [comment]
@SteveSandersonMS How many of the route constraints are supported? Here's our ASP.NET Core list: https://docs.microsoft.com/aspnet/core/fundamentals/routing#route-constraint-reference

**Comment by guardrex** [comment]
@danroth27 Is it an accurate guess that all of our route params are supported?

**Comment by danroth27** [comment]
@guardrex No, I believe we only support a subset.
