### ISSUE TITLE
Please add sample how can be invoked .net instance method from js with parameters

### ISSUE THREAD

**Issue by Lupusa87** [aspnet/Blazor.Docs#220]
There is provided [sample](https://blazor.net/docs/javascript-interop.html) about this but I ask for sample with will show how to use parameters when invoking .net method from js.

**Comment by bmsantos** [comment]
@Lupusa87, its available in the same [page](https://blazor.net/docs/javascript-interop.html#invoke-net-methods-from-javascript-functions)

Here's a sample where I pass an ID and an object with geolocation position details:

```typescript
 DotNet.invokeMethodAsync('Bionic.Bridge.Capacitor', 'ReportNewPosition', this.id, position);
```

And the respective method in C#:
```c#
namespace Bionic.Bridge.Capacitor {
    public static class GeolocationBridge {
        [JSInvokable]
        public static void ReportNewPosition(string watcherId, GeolocationPosition newPosition) =>
            watchers[watcherId](newPosition);
    }
}
```

**Comment by Lupusa87** [comment]
Thank you.

I was asking about invoking instance method not static method.

However your sample helped me a lot and I fixed this issue.

**This is instance method syncronous invoking.**

JsInteropFunctions.cs
```
public static bool JsPingInstance(string a)
 {
  DotNetObjectRef dotnethelper = new DotNetObjectRef(new InstanceFunctions());

   return (JSRuntime.Current as IJSInProcessRuntime).Invoke<bool>(
    "exampleJsFunctions.JsPingInstance",new { dotnethelper, a });
 }
```

InstanceFunctions.cs:
```
 [JSInvokable]
 public static void MethodInstance(string a, string b)
  {
     Console.WriteLine(a + " " b);
  }
```
JsInterop.js:
```
window.exampleJsFunctions = {
    JsPingInstance: function (obj) {
        obj["dotnethelper"].invokeMethod('MethodInstance', obj["a"], "america");
        return true;
    }
};
```
