### ISSUE TITLE
Wording in Interop help

### ISSUE THREAD

**Issue by kant2002** [aspnet/Blazor.Docs#257]
Blazor docs on page https://blazor.net/docs/javascript-interop.html has following text.

```
The IJSRuntime abstraction is asynchronous to allow for out-of-process scenarios.
If the app runs in-process and you want to invoke a JavaScript function synchronously, 
downcast to IJSInProcessRuntime and call Invoke<T> instead. We recommend that 
most JavaScript interop libraries use the async APIs to ensure the libraries are available 
in all Blazor scenarios, client-side or server-side.
```

I'm a confused by the term in-process and out-of-process scenarios. It is not clear is client-side code considered in-process , or out-of-process by the team. Would be good to clarify that point.

**Comment by guardrex** [comment]
@kant2002 Thanks for commenting. I agree.

@danroth27 Should it go like ...

> to allow for out-of-process server-side scenarios. If the app runs in-process on the server and you want to invoke a JavaScript function synchronously, ...

Otherwise, it might work if the out-of-process/in-process language is dropped and just say ...

> The `IJSRuntime` abstraction is asynchronous. If you want to invoke a JavaScript function synchronously, ...
