### ISSUE TITLE
Add infrastructure for generating API ref docs from the Blazor NuGet packages

### ISSUE THREAD

**Issue by danroth27** [aspnet/Blazor.Docs#26]
We shouldn't have the Blazor assemblies checked into the docs repo. Instead we should have some automation that restores the Blazor packages and extracts the Blazor assemblies and XML doc files that we can then run docfx on.

**Comment by guardrex** [comment]
@danroth27 Since this will be resolved automatically with the move to official docs, do you still want to keep this as an open work item?

**Comment by danroth27** [comment]
Nah
