### ISSUE TITLE
Improve debugging documentation with troubleshooting tips

### ISSUE THREAD

**Issue by mattferderer** [aspnet/Blazor.Docs#269]
From watching videos & messing around with the debugging tool it appears that 

* it only works in HTTP, not HTTPS apps
* You may need to run localStorage.clear() on the debugging window

Is this correct? If so would you accept a pull request that suggests these troubleshooting tips?

This is the documentation in question: https://github.com/aspnet/Blazor.Docs/blob/master/docs/debugging.md/#L1

**Comment by guardrex** [comment]
@danroth27

**Comment by danroth27** [comment]
Yup, we would be happy to consider a pull request to clarify this topic and some of the known issues with debugging.
