### ISSUE TITLE
Data binding methods with parameters

### ISSUE THREAD

**Issue by MorneZaayman** [aspnet/Blazor.Docs#296]
I would like to make an improvement to the Data binding section of Components. It currently does not indicate how to pass parameters in methods. This can be accomplished using the `@(() => Method(parameter))` syntax. This could also be supplemented by an example.

**Comment by guardrex** [comment]
@danroth27

**Comment by guardrex** [comment]
@MorneZaayman ... Sorry for the delay ... we were all 🏃🏃🏃🏃😅 for the 2.2 release ... and then the holidays 🎁 hit.

Would you like to go ahead with a PR? If so ...

You can edit the document on GH and create the PR right here online. https://github.com/aspnet/Blazor.Docs/blob/master/docs/components/index.md :point_right: click the ✏️ icon on the right to edit the topic. After changing the text, commit the changes and create the PR from there. You can title the commit and the PR with the same title you used here, *Data binding methods with parameters*.

At the top of your PR opening comment, include `Fixes #296`, and that will auto-close this issue if the PR is accepted and merged.

WRT the content ...

Add the content at the end of the **Data binding** section under an emphasized heading (`** HEADING **`), just like `**Format strings**` and `**Component parameters**` in that section.

For sample code, provide it with content code blocks ...

> \`\`\`cshtml
> CSHTML code here
> \`\`\`

I'll take a look at the code example that you provide for the next sample app update.

Let me know if you have any ❓❓❓❓.

**Comment by guardrex** [comment]
Sure thing @MorneZaayman. You might want to wait until https://github.com/aspnet/Blazor.Docs/pull/349 merges first. It touches the topic, so you can avoid a merge conflict. I think that will be reviewed and merged soon-ish ... maybe by the end of the week.

**Comment by Andrzej-W** [comment]
@MorneZaayman you can also add example for async syntax and more than one parameter, including event parameters:
`@(async (e) => Method(e, parameter))`
