### ISSUE TITLE
Introducing Design Patterns 

### ISSUE THREAD

**Issue by vertonghenb** [aspnet/Blazor.Docs#301]
Requests for new topic

Since Server-side Blazor (a.k.a Razor Components)  shifts the entire idea of a client and back-end, it would be nice to see some advised Design Patterns. For example: https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/microservice-ddd-cqrs-patterns/net-core-microservice-domain-model
- Is it still feasable to use a DDD pattern when we're sharing the domain between the App and Server?
- Should the Service Layer be isolated from the domain so we can use a Proxy Design Pattern when switching from Server Side to Client Side?
- Rich domain model versus anemic domain model (https://martinfowler.com/bliki/AnemicDomainModel.html)
- Form Validation based on Data Annotations and taking a dependency on MVC or using a library such as FluentValidation?
- ...

For newcomers it can be pretty confusing.

**Comment by guardrex** [comment]
@danroth27

**Comment by guardrex** [comment]
Issue moved to aspnet/Docs.
