### ISSUE TITLE
Add a library for Payment Requests

### ISSUE THREAD

**Issue by philipblaquiere** [aspnet/Blazor.Docs#302]
I'd like to share the library I created to call browser's PaymentRequests. It attempts to follow the standard defined by w3c.

https://github.com/philipblaquiere/Blazor.Payments

**Comment by guardrex** [comment]
Thanks @philipblaquiere ... I'll take care of this next weekend.

**Comment by guardrex** [comment]
I've tacked this on to an existing PR that updates the community topic.
