### ISSUE TITLE
Update JS interop to document appropriate use of IJSRuntime with server-side Blazor

### ISSUE THREAD

**Issue by danroth27** [aspnet/Blazor.Docs#326]
https://github.com/aspnet/Blazor/issues/1726#issuecomment-441777114

`JSRuntime.Current` always refers to the current user's request. Instead, do the following instead in your component: `@inject IJSRuntime jsRuntime`, and then use jsRuntime to issue the JS interop call instead. That way you'll be sending the info to each client separately.

**Comment by guardrex** [comment]
This issue was addressed on the move and will be reviewed on aspnet/Docs.
