### ISSUE TITLE
404 on Get Started :(

### ISSUE THREAD

**Issue by peterennis** [aspnet/Blazor.Docs#344]
![capture473](https://user-images.githubusercontent.com/140737/50267478-321d9a00-03dc-11e9-84b1-7b383172f7fa.png)

![capture472](https://user-images.githubusercontent.com/140737/50267060-c8e95700-03da-11e9-81d0-8a12f395fda5.png)

**Comment by guardrex** [comment]
Hello @peterennis ... Don't use the GitHub preview. The relative links only work on the live site.

Use :point_right: https://blazor.net/
