### ISSUE TITLE
Request for new entry in Book section

### ISSUE THREAD

**Issue by proudmonkey** [aspnet/Blazor.Docs#345]
Can I add my free ebook entitled "Dockerizing ASP.NET Core and Blazor Applications on Mac". The link is here: https://www.c-sharpcorner.com/ebooks/dockerizing-asp-net-core-and-blazor-applications-on-mac

Thank you,
Vinz

**Comment by guardrex** [comment]
Sure @proudmonkey ... Go ahead. Put `Fixes #345` in the PR's comment.

The lists on the Community page are alphabetical. Add it using this format to the *Books* section:

```
* [TITLE](LINK) &ndash; DESCRIPTION
```

**Comment by guardrex** [comment]
**_Done!_** :point_right: #346

**Comment by proudmonkey** [comment]
Thank you @guardrex for adding this. I am on vacation and I have limited access to internet.

**Comment by proudmonkey** [comment]
Hi @guardrex, 

I see that this one was closed and merged however, i can't seem to find the link from the list.

**Comment by guardrex** [comment]
Hasn't gone live yet. I'll merge to live now.

**Comment by proudmonkey** [comment]
Wonderful! Thanks man!
