### ISSUE TITLE
Component input validation

### ISSUE THREAD

**Issue by guardrex** [aspnet/Blazor.Docs#358]
@danroth27 Should we add Hisham's blog post for validation of Component input to the Community page (perhaps *Components* topic page, too), or should we schedule a *Components* node subtopic to cover something along these lines?

http://www.hishambinateya.com/part1-validation-controls-using-blazor-basic-validation-controls

**Comment by danroth27** [comment]
I'm happy to link to @hishamco's stuff from the Blazor community page, but we should wait for the [Blazor forms and validation work](https://github.com/aspnet/AspNetCore/issues/5460) before adding anything to the component docs.

**Comment by guardrex** [comment]
:+1: Will do.

**Comment by hishamco** [comment]
Thanks for that @danroth27, also I planned to write another blog post if I got a time for showing a Model Validation

BTW how can I participate to add links in community links for Blazor, because I was planned to add some stuff that I'm doing in Blazor last few weeks?

**Comment by hishamco** [comment]
@guardrex FYI I did another blog post on [Part II: Validation Controls using Blazor - Custom Validation Controls
](http://www.hishambinateya.com/part2-validation-controls-using-blazor-custom-validation-controls) may be it helps

**Comment by hishamco** [comment]
But at least we need to collect some articles about `Balzor Validation` if any to show the help the community how we can doing validation with the current release of Blazor - while it isn't supported yet
