### ISSUE TITLE
Add the doc for bind-property-event syntax

### ISSUE THREAD

**Issue by Andrzej-W** [aspnet/Blazor.Docs#368]
Here https://github.com/aspnet/AspNetCore/issues/5521 is a discussion about a bug in data binding. Notice the syntax: `bind-value-oninput=@myField` and a few other examples. It is not documented at all and should be added here: https://blazor.net/docs/components/index.html#data-binding

First, someone from Blazor team should tell us whether in the foreseeable future it will work as expected and what is really expected. Is this universal syntax in the form `bind-property-event` or only `bind-value-event`. It is **probably** designed only for HTML elements and not for user defined components. Which HTML elements?
- input (what type? text, password, checkbox, etc., new HTML types: date, time, number, email, etc.)
- textarea
- select

cc: @SteveSandersonMS

**Comment by guardrex** [comment]
Thanks @Andrzej-W ... I'll wait until we hear from @SteveSandersonMS on the questions you asked. However, some quick testing should also be able to determine what's supported if I get to this before he responds. I might have some time next weekend to take a look at this issue.

**Comment by Andrzej-W** [comment]
@guardrex Quick testing in Blazor 0.7 is unfortunately not enough - usually you will get `Error: System.InvalidCastException: Specified cast is not valid.` (https://github.com/aspnet/AspNetCore/issues/5521#issuecomment-450136807)

**Comment by guardrex** [comment]
Yes, I mean that it "isn't supported" if an error is thrown, so we wouldn't document anything for the current release that doesn't work.

**Comment by guardrex** [comment]
Issue as been moved to aspnet/Docs.
