### ISSUE TITLE
Add new sample (Blazor Excel)

### ISSUE THREAD

**Issue by Lupusa87** [aspnet/Blazor.Docs#372]
If you like please add this to samples list.

https://lupblazordemos.z13.web.core.windows.net/ExcelPage

https://github.com/Lupusa87/BlazorExcel

![untitled](https://user-images.githubusercontent.com/40779557/51091236-00d38800-1756-11e9-9311-44baa5af6e34.png)

**Comment by guardrex** [comment]
@Lupusa87 I don't think we can add this because "Excel" is a registered trademark of Microsoft Corp. You could change it to something like "Blazor Spreadsheet" or "Blazor Calc" ... **_something that won't get us locked up!_** 👮🚓 lol

**Comment by Lupusa87** [comment]
Sorry I did not thought about this.

I have updated name as you suggested.

https://lupblazordemos.z13.web.core.windows.net/SpreadsheetPage

https://github.com/Lupusa87/BlazorSpreadsheet

Thank you

**Comment by lohithgn** [comment]
@Lupusa87 instead of asking @guardrex to update the community samples page - you should do the following:
- fork the Blazor.Docs repo
- update the community samples with your addition
- create a PR

@guardrex will then just merge it to live … that's what most of us do when we need to add our samples to community samples page. Per se - we don't open an issue for this :)

hope this helps

**Comment by Lupusa87** [comment]
I have another new samples too, where should I open new issues here or in https://github.com/aspnet/Docs/tree/master/aspnetcore/razor-components?

  For example https://lupblazordemos.z13.web.core.windows.net/PerformanceChartPage

**Comment by guardrex** [comment]
It's no serious bother @lohithgn ... only takes a few minutes. Besides, I frequently need to update the format and language to conform to our guidelines, so I end up having to edit most of them.

@Lupusa87 ... thanks ... I'll get that in there in a few minutes. Thanks.

We narrowly avoided getting the 🔪 there! lol ...We don't want to invoke the wrath of CELA attorneys! 😨

**Comment by lohithgn** [comment]
still @guardrex - you can utilize those minutes for real issues :)

**Comment by Lupusa87** [comment]
@lohithgn Thank you for advise, you are right but I don't have big experience in PRs :) Will try.

 For now it is not clear where should I do this, because as I see repo is changing.

**Comment by guardrex** [comment]
@lohithgn I'm **_SURE_** that the .NET Foundation and MS management would agree! 😀 $$$ 💰 $$$

The plan is that the Community page is going to move, but not at the moment. Dan's working on that and will let us know. For now, we'll just keep updating here on Blazor.Docs.

**Comment by lohithgn** [comment]
@Lupusa87 if you go to this page - https://blazor.net/community.html … it has a link called Improve this doc. That will point you to the repo. Even if the team changes the repo, the link will always point to the right place. That's what we all do. Trivial thing like this should be no brainer.

**Comment by guardrex** [comment]
Yes ... the format for each section is easy to see now because there are so many entries. Just copy and paste one of the others in the same section and then modify it with the correct title, links, description.

**Comment by lohithgn** [comment]
@lohithgn may be i should do a video … hmmm … something for my backlog ;)
