### ISSUE TITLE
Link API references in topics to API ref docs

### ISSUE THREAD

**Issue by guardrex** [aspnet/Blazor.Docs#38]
Link API references to the API topics.

**Comment by danroth27** [comment]
@guardrex Why is this blocked? Even without the automation, we have API refs in our docs already, right?

**Comment by guardrex** [comment]
We don't for API. I only held off because you mentioned that you were going to change the way API docs are built (i.e., not just assemblies pushed to the repo). Therefore, I guessed (perhaps incorrectly) that the links to API topics might change. Right now, Blazor API mentions are merely code fenced. If you'd like them linked now, no problem ... I'll take care of it.

**Comment by guardrex** [comment]
Ok ... sounds good. I'll find a few free minutes this weekend to update the references.

**Comment by danroth27** [comment]
It's not urgent or high priority. Feel free to spend those extra minutes on yourself :smile:
