### ISSUE TITLE
Razor Components + EF Core

### ISSUE THREAD

**Issue by vertonghenb** [aspnet/Blazor.Docs#400]
Currently there is a good tutorial about using Blazor + EF Core. However for Razor Components there is no such tutorial / guideline. Since the entire idea of DI changes when using Razor Components it would be nice to see an article describing best practises for a combination with EF Core. Since it doesn't make a lot of sense to use Razor Components with a `Scoped` version of the `DbContext`. However what is the prefered way to handle EF Core's DI in Razor Components? 
- Singleton?
- Transient?
- Scoped?

**Comment by guardrex** [comment]
Hello @vertonghenb ... See the DI topic for the latest guidance from engineering ... https://blazor.net/docs/dependency-injection.html#add-services-to-di

> ASP.NET Core Razor Components support the Scoped lifetime. In a Razor Component, a scoped service registration is scoped to the connection. For this reason, using scoped services is preferred for services that should be scoped to the current user (even if the current intent is to run client-side in the browser).

WRT a tutorial and/or additional content for this, that will be under discussion after the docs are moved over to the official repo. We'll likely expand the coverage.

We're in the process of closing down this repo, so I'm going to close here.
