### ISSUE TITLE
Redirection to newer getting started tutorial

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Blazor.Docs#441]
As you are probably aware, the `docs/tutorials/build-your-first-blazor-app.md` should redirect to `https://docs.microsoft.com/aspnet/core/tutorials/build-your-first-razor-components-app`,
but it seems that resulting documentation page is not rendered correctly:
https://blazor.net/docs/tutorials/build-your-first-blazor-app.html

Let's figure out redirection in DocFX

**Comment by peterblazejewicz** [comment]
Just realized current docs are now using standard documentation pages, so there is simply cached content. Still better should be just a markdown link on that page

**Comment by guardrex** [comment]
We're going to be dumping this repo entirely soon. At that time, we'll be redirecting at the domain-level.

This one was missing a quote. Thanks for letting me know. I'll patch that now.
