### ISSUE TITLE
JavaScript and TypeScript interop

### ISSUE THREAD

**Issue by guardrex** [aspnet/Blazor.Docs#59]
Title: Blazor JavaScript and TypeScript interop
Path: docs/javascript-typescript-interop.md
UID: client-side/blazor/javascript-typescript-interop
TOC: `JavaScript/TypeScript interop` between `Dependency Injection` and `Host and deploy`

Add to *toc.md* and to the docs *index.md* page in the same spot as the TOC.

**Comment by danroth27** [comment]
# Improved .NET and JavaScript interoperability.

In some scenarios, when building a Blazor application you'll have to invoke JavaScript functions from .NET and .NET methods from JavaScript code. Blazor includes support for these two scenarios, calling JavaScript functions from C# and calling .NET methods from JavaScript.

## Invoking JavaScript functions from .NET

There are times when your Blazor .NET code needs to call some JavaScript code, for example to expose some platform specific capability to the .NET application. For these cases, you can use the `T Invoke<T>(functionName, args)` and `Task<T> InvokeAsync<T>(functionName, args)` methods in the RegisteredFunction class to invoke a given set of functions registered with Blazor on the JavaScript side by calling `Blazor.registerFunction('functionName',functionImplementation)`. For example:

```js
Blazor.registerFunction(
    'echo',
    function(message){
        return message;
    });

Blazor.registerFunction(
    'echoAsync',
    function(message){
        return Promise.Resolve(message);
    });
```

```csharp
var helloWorld = RegisteredFunction.Invoke<string>("echo","Hello world!");
var helloWorldAsync = await RegisteredFunction.InvokeAsync<string>("echoAsync","Hello world async!");
```
The JavaScript snippet above, registers the given functions as 'echo' and 'echoAsync' with the Blazor runtime.
Then, on the C# snippet, the functions are invoked by calling Invoke and InvokeAsync respectively passing in the function name (echo and echoAsync) and the desired message to reply back.

##Invoking .NET methods from JavaScript
In some scenarios JavaScript code in the browser needs to call .NET methods, for example when a callback in JavaScript is triggered. This can be achieved by using the functions `Blazor.invokeDotNetMethod` and `Blazor.invokeDotNetMethodAsync` from JavaScript. These two functions allow JavaScript to call sync and async .NET methods respectively. These methods must be static, non-generic, must not be overloaded and all the method parameters must be concrete types and deserializable using JSON. For example:

```csharp
namespace Alerts
{
    public class Timeout
    {
        public static void TimeoutCallback()
        {
            Console.WriteLine('Timeout triggered!');
        }
    }
}
```

```javascript
Blazor.invokeDotNetMethod({
    type: {
        assembly: 'MyTimeoutAssembly',
        name: 'Alerts.Timeout'
    },
    method: {
        name: 'Timeoutcallback'
    }
})
```

**Comment by danroth27** [comment]
@rstropek Are you still interested in taking this one on?

If not, @guardrex do you want this one or should I go ahead and put together PR for it?

**Comment by danroth27** [comment]
This topic should also cover putting the JS interop code in a Blazor class library (`dotnet new blazorlib`) so you can easily share it as a NuGet package.

**Comment by danroth27** [comment]
@guardrex I can't think of anything more relaxing than writing Blazor docs! 😄

**Comment by guardrex** [comment]
@danroth27 We haven't heard back, so I'm going to work on this one today (Saturday). I should have it submitted either tonight or tomorrow.
