### ISSUE TITLE
Sidebar topic nav "active" class on wrong list item

### ISSUE THREAD

**Issue by guardrex** [aspnet/Blazor.Docs#69]
The "active" class is hitting the wrong list item. The UI scrolls to the right spot, but it highlights the wrong entry.

For the following example, I clicked on "Build a todo list" ... "Dependency injection" is receiving the "active" CSS class.

![capture](https://user-images.githubusercontent.com/1622880/39008933-bfed46c8-43cf-11e8-84a0-5d7d7aa513b4.PNG)

cc/ @danroth27

**Comment by danroth27** [comment]
Looks like a potential docfx issue. I see this happening on https://dotnet.github.io/docfx as well.

**Comment by guardrex** [comment]
... shall I open on their repo?

**Comment by danroth27** [comment]
Yeah, and point out the same issue is happening on their site.

We can use this issue to track investigating workarounds.

**Comment by guardrex** [comment]
Fixed by https://github.com/dotnet/docfx/pull/2665
