### ISSUE TITLE
Add topic on building component libraries

### ISSUE THREAD

**Issue by danroth27** [aspnet/Blazor.Docs#70]
We should have a topic around the new component library template that shows how to build, package, and share libraries of components.

See https://blogs.msdn.microsoft.com/webdev/2018/04/17/blazor-0-2-0-release-now-available/ for some existing content.

**Comment by danroth27** [comment]
Changing this from a tutorial to a topic. Might be good to have a tutorial at some point as well, but I'd like a normal topic first.

**Comment by danroth27** [comment]
@stimms Sounds great! I would just use the content in the Blazor Class Library (blazorlib) template. It already contains a component and shows how you can include static assets.

Here's a brain dump of what I would expect to see in this doc:
- Components are just .NET types and component libraries are just normal .NET assemblies
- Create component libraries using the Blazor Class Library template (`dotnet new blazorlib`)
- Component libraries can include static assets, like JS, CSS, images, etc.
- Packaging component libraries and sharing via NuGet
- Consuming component libraries (add package, use temporary `@addTagHelpers` workaround)

**Comment by peterblazejewicz** [comment]
> * Component libraries can include static assets, like JS, CSS, images, etc.

👍

**Comment by guardrex** [comment]
@stimms If you have any questions on the topic+sample setup for the repo, feel free to ping me.
