### ISSUE TITLE
Add topic on calling web APIs from Blazor

### ISSUE THREAD

**Issue by danroth27** [aspnet/Blazor.Docs#71]
- `HttpClient`
- JSON helpers
- Setting fetch arguments for the request (see https://github.com/aspnet/Blazor/pull/399#issuecomment-377193365)
- Making cross origin request

**Comment by stimms** [comment]
This sounds interesting. Do we want to surface the fact that the HttpClient is not the actual HttpClient and is actually fetch or is the feeling that the abstraction is so good nobody needs to know?

**Comment by guardrex** [comment]
Issue moved to aspnet/Docs.
