### ISSUE TITLE
Add section to components article on using a code behind file

### ISSUE THREAD

**Issue by danroth27** [aspnet/Blazor.Docs#73]
We should document how to setup a code behind file using `@inherits`. Later, we can update this section when we implement support for partials (https://github.com/aspnet/Blazor/issues/278)

**Comment by guardrex** [comment]
@danroth27 We had it for a bit but cut it temporarily. Here's what we cut ... would this suffice?

Note: I also cut *BlazorRocks.cshtml* and *BlazorRocksBase.cs* out of the sample app, but I have the files here, so I can shoot them back into the sample with the section.

## Base class inheritance for a "code-behind" experience

Blazor's Razor files (*\*.cshtml*) mix HTML markup and C# processing code in the same file. The `@inherits` directive can be used to provide Blazor with a "code-behind" experience that separates view markup from processing code.

The [Components Sample app](https://github.com/aspnet/Docs/tree/master/aspnetcore/client-side/blazor/components/common/samples/) shows how a component can inherit a base class, `BlazorRocksBase`, to provide its properties and methods.

*BlazorRocks.cshtml*:

[!code-cshtml[](common/samples/2.x/ComponentsSample/Pages/BlazorRocks.cshtml?start=1&end=8)]

... it shows this ...

```csharp
using Microsoft.AspNetCore.Blazor.Components;

public class BlazorRocksBase : BlazorComponent
{
    public string BlazorRocksText { get; set; } = 
        "Blazor rocks the browser!";
}
```

*BlazorRocksBase.cs*:

[!code-cshtml[](common/samples/2.x/ComponentsSample/Pages/BlazorRocksBase.cs)]

... it shows this ...

```cshtml
@page "/BlazorRocks"
@inherits BlazorRocksBase

<h1>@BlazorRocksText</h1>
```

The base class must derive from `BlazorComponent` in the `Microsoft.AspNetCore.Blazor.Components` namespace.
