### ISSUE TITLE
Add PDF Export

### ISSUE THREAD

**Issue by jongalloway** [aspnet/Blazor.Docs#76]
Would be nice to be able to export docs to PDF. [DocFx supports PDF export](https://dotnet.github.io/docfx/tutorial/walkthrough/walkthrough_generate_pdf.html), but has a dependency on [wkhtmltopdf](https://wkhtmltopdf.org/) which might be a little hard to integrate with the GitHub pages hosting.

I *think* the way to do this would be to integrated it into the AppVeyor build. There's a Chocolatey package for wkhtmltopdf, and AppVeyor supports Chocolatey installs, so that may be one way to do it. Another is just to use the [wphtmltopdf installer](https://wkhtmltopdf.org/downloads.html).

Once that dependency is in place, we just need to [add a *pdf* section to our docfx.json file](https://dotnet.github.io/docfx/tutorial/walkthrough/walkthrough_generate_pdf.html#step2-add-pdf-section-into-docfxjson) and we'll have a PDF generated.

**Comment by jongalloway** [comment]
I've got this started in a [private fork](https://github.com/jongalloway/Blazor.Docs). PDF export is working, need to tweak the PDF toc.yml but the plumbing is set up.

**Comment by guardrex** [comment]
@jongalloway Would you like me to take a stab at getting PDF gen to work?

**Comment by jongalloway** [comment]
@guardrex If you have time to, sure. Check out the fork I linked to - I had the export working but the toc needs to be improved.

**Comment by guardrex** [comment]
🛑 **_Blocked!_** 🛑 https://github.com/dotnet/docfx/issues/3446 will require resolution before we can proceed.

**Comment by guardrex** [comment]
The DocFX cats have marked the blocking issue on their repo as up-for-grabs/needs-help, so I don't anticipate it getting resolved anytime soon. This isn't an actionable issue for quite some time on that basis; and with the move to official docs, we wouldn't support PDFs OOB anyway. I'm going to close; but re-open if I've erred in doing so.
