### ISSUE TITLE
Child content section of the Components page should be updated

### ISSUE THREAD

**Issue by ivryakhov** [aspnet/Blazor.Docs#85]
Hi,

it was founded a kind of typo in the **Child content** section of the **Components** page:

_ChildComponent.cshtml:_

```
<div class="panel panel-success">
  <div class="panel-heading">@Title</div>
  <div class="panel-body">@PanelContent</div>
</div>

@functions {
    public string Title { get; set; }
    public RenderFragment **PanelContent** { get; set; }
}
```
I got a fault when trying to execute this example. After a discussion in an issue report https://github.com/aspnet/Blazor/issues/686 it was founded the **PanelConent** field's name is incorrect. It is suggested to rename this to **ChildContent**. Unfortunatelly, there are still some errors with this name using. As a result I'm not sure how this example should be improved.

**Comment by guardrex** [comment]
Thanks @ivryakhov!

Yes, thank you for reporting ... I'll take a look at this in a couple of hours and get it fixed fast.

> But there are still some errors in the console:

> Uncaught (in promise) Error: System.InvalidOperationException: Unable to set property 'ChildContent' on object of type 'WebApplication1.Pages.ChildComponent'. The error was: Object of type 'Microsoft.AspNetCore.Blazor.RenderFragment' cannot be converted to type 'WebApplication1.Pages.RenderFragment'. ---> System.ArgumentException: Object of type 'Microsoft.AspNetCore.Blazor.RenderFragment' cannot be converted to type 'WebApplication1.Pages.RenderFragment'.

**Comment by SteveSandersonMS** [comment]
@guardrex The other errors are unrelated and can be ignored. Thanks for fixing this!

**Comment by guardrex** [comment]
Thanks again @ivryakhov for reporting. I fixed it in two spots (in the sample code and in the sample markup that explains the code).

@SteveSandersonMS I was surprised that it broke because I incorrectly assumed that *ChildComponent.cshtml* could have its `RenderFragement` property be named anything. Does the name of the property need to pair with the name of the component?

I understand the first pair ...

\<**Child**Component ... /> :point_right: **Child**Component.cshtml :point_right: **Child**Content `RenderFragment`

... is the second pair also a convention? If so, then I'll flesh that fact out more in the topic.

**Comment by guardrex** [comment]
> The name of the parameter that receives child content is always ChildContent, regardless of the name of anything else.

Ahhhh! Ok ... I'll make that explicit in the topic. I'll ping u on the PR.

**Comment by ivryakhov** [comment]
Great! @guardrex thank you for the document update.

**Comment by ivryakhov** [comment]
I just have found probably another missprint on the page, section **Component attributes**.
@guardrex is it suitable to report this inside this issue?

Child component:
```
<div> ... </div>

@functions {
    public int Year { get; set; }
    public Action<int> ValueChanged { get; set; }
}
```
Actually, the second property's name should be **YearChanged**. In other case, where is a corresponding error message in a browser's console:

> Uncaught (in promise) Error: System.InvalidOperationException: Object of type 'WebApplication1.Pages.ChildComponent' does not have a property matching the name 'YearChanged'.

**Comment by guardrex** [comment]
@ivryakhov Great :eye:!

That came from the blog post: https://blogs.msdn.microsoft.com/webdev/2018/04/17/blazor-0-2-0-release-now-available/#binding-to-components

... and there is one line under the example that I didn't address in the topic example ...

> The `Value` parameter is bindable because it has a companion `ValueChanged` event that matches the type of the `Value` parameter.

I've made a commit to the PR to change it to `YearChanged`. I also took Steve's line and added it to this section of the topic.

**Comment by ivryakhov** [comment]
@guardrex thank you for the fix!
